# Licensed to the Fintech Open Source Foundation (FINOS) under one or
# more contributor license agreements. See the NOTICE file distributed
# with this work for additional information regarding copyright ownership.
# FINOS licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

config:
  tenants: trac-metadb-tenants.yaml
  secret.type: PKCS12
  secret.url: secrets.pfx

# Environment settings are verified in one of the test cases so they need to match
# MetadataReadApiTest platformInfo()
platformInfo:
  environment: TEST_ENVIRONMENT
  production: false
  deploymentInfo:
    region: UK

metadataStore:
  protocol: JDBC
  properties:
    format: PROTO
    dialect: MYSQL
    jdbcUrl: //metadb:3306/trac
    mysql.user: trac_admin
    pool.size: 2
    pool.overflow: 5
  secrets:
    mysql.password: metadb_secret

jobCache:
  protocol: JDBC
  properties:
    dialect: MYSQL
    jdbcUrl: //metadb:3306/trac
    mysql.user: trac_admin
    pool.size: 2
    pool.overflow: 5
  secrets:
    mysql.password: metadb_secret

services:

  metadata:
    port: 8081

  admin:
    port: 8084

deployment:
  layout: SANDBOX
