

storage:

  external:

    data_integration:
      protocol: SQL
      properties:
        dialect: MARIADB
        driver.python: alchemy
        alchemy.url: mysql+pymysql://metadb:3306/trac
        alchemy.username: trac_admin
        alchemy.password: DB_SECRET
