name: Basic Build

on: [push, pull_request]

jobs:

  platform_build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x

    # fetch-depth = 0 is needed to get tags for version info
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: ./gradlew build -x test

    - name: Unit Tests
      run: ./gradlew test

  python_runtime:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Testing targets for the Python model runtime
    # Include the latest stable release (3.9)
    # Oldest supported version is 3.6, this is required by Pandas 1.0
    # (also note Python 3.5 is EOL, final release 3.5.10 was in September 2020)
    # Do not include 2.7 - that ship has sailed!
    strategy:

      # Try to finish all jobs - it can be helpful to see if some succeed and others fail
      fail-fast: false

      matrix:
        enviroment:

          - { ENV_NAME: "Latest: Python 3.9, PySpark 3.0.x, Pandas 1.x",
              PYTHON_VERSION: "3.9",
              PYSPARK_VERSION: ">= 3.0.0, < 3.1.0",
              PANDAS_VERSION: ">= 1.1.0, < 2.0.0",
              PYPANDOC: false }

          - { ENV_NAME: "Oldest: Python 3.7, PySpark 2.4.0, Pandas 1.0.0",
              PYTHON_VERSION: "3.7",
              PYSPARK_VERSION: "== 2.4.0",
              PANDAS_VERSION: "== 1.0.0",
              PYPANDOC: true }

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.enviroment.PYTHON_VERSION }}

      - name: PIP Upgrade
        run: python -m pip install --upgrade pip

      # fetch-depth = 0 is needed to get tags for version info
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Use a venv so build tool dependencies don't get mixed with the main build
      - name: Install dependencies for build tools
        run: |
          cd dev/
          python -m venv venv/
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Protoc code generation
        run: |
          cd dev/
          . venv/bin/activate
          python codegen/protoc-ctrl.py python_runtime --proto_path trac-api/trac-metadata/src/main/proto --out trac-runtime/python/generated/trac/rt_gen/domain
          python codegen/protoc-ctrl.py python_proto --proto_path trac-api/trac-metadata/src/main/proto --out trac-runtime/python/generated/trac/rt_gen/proto

      # PyPanDoc dependency is not managed correctly by PySpark 2.4 package
      # It needs to be installed explicitly first
      - name: Install pre-req dependencies
        if: ${{ matrix.enviroment.PYPANDOC }}
        run: |
          cd trac-runtime/python
          python -m pip install --upgrade pip
          pip install pypandoc

      - name: Install dependencies
        run: |
          cd trac-runtime/python
          python -m pip install --upgrade pip
          pip install "pyspark ${{ matrix.enviroment.PYSPARK_VERSION }}"
          pip install "pandas ${{ matrix.enviroment.PANDAS_VERSION }}"
          pip install -r requirements.txt

      - name: Unit tests
        run: |
          export PYTHONPATH=trac-runtime/python/generated
          export PYTHONPATH=trac-runtime/python/src:$PYTHONPATH
          export PYTHONPATH=trac-runtime/python/test:$PYTHONPATH
          python -m unittest discover -s trac-runtime/python/test/trac_test -t trac-runtime/python/test

      - name: Python example models
        run: |
          export PYTHONPATH=trac-runtime/python/generated
          export PYTHONPATH=trac-runtime/python/src:$PYTHONPATH
          export PYTHONPATH=trac-runtime/python/test:$PYTHONPATH
          python -m unittest discover -s trac-runtime/python/test/trac_examples -t trac-runtime/python/test

      - name: Build packages
        run: |
          cd trac-runtime/python
          python setup.py sdist bdist_wheel

  web_api:

    runs-on: ubuntu-latest

    steps:

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    # fetch-depth = 0 is needed to get tags for version info
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        cd trac-api/packages/web
        npm install

    - name: Set TRAC version
      run: |
        cd trac-api/packages/web
        npm run tracVersion:posix

    - name: PBJS code generation
      run: |
        cd trac-api/packages/web
        npm run pbjs
        npm run pbts

  documentation:

    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: PIP Upgrade
        run: python -m pip install --upgrade pip

      # fetch-depth = 0 is needed to get tags for version info
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies for build tools
        run: |
          cd dev/
          pip install -r requirements.txt

      - name: Run all docgen targets
        run: |
          cd dev/
          python docgen/docgen-ctrl.py all
