name: Basic Build

on: [push, pull_request]

jobs:

  platform_build:

    runs-on: ubuntu-latest

    steps:

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x

    # fetch-depth = 0 is needed to get tags for version info
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: ./gradlew build -x test

    - name: Unit Tests
      run: ./gradlew test

  python_runtime:

    runs-on: ubuntu-latest

    # Testing targets for the Python model runtime
    # Include the latest stable release (3.9)
    # Oldest supported version is 3.6, this is required by Pandas 1.0
    # (also note Python 3.5 is EOL, final release 3.5.10 was in September 2020)
    # Do not include 2.7 - that ship has sailed!
    strategy:

      # Try to finish all jobs - it can be helpful to see if some succeed and others fail
      fail-fast: false

      matrix:
        enviroment:

          - { ENV_NAME: "Latest: Python 3.9, PySpark 3.0.x, Pandas 1.x",
              PYTHON_VERSION: "3.9",
              PYSPARK_VERSION: ">= 3.0.0, < 3.1.0",
              PANDAS_VERSION: ">= 1.1.0, < 2.0.0",
              PYPANDOC: false }

          - { ENV_NAME: "Oldest: Python 3.6, PySpark 2.4.0, Pandas 1.0.0",
              PYTHON_VERSION: "3.6",
              PYSPARK_VERSION: "== 2.4.0",
              PANDAS_VERSION: "== 1.0.0",
              PYPANDOC: true }

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.enviroment.PYTHON_VERSION }}

      # fetch-depth = 0 is needed to get tags for version info
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # PyPanDoc dependency is not managed correctly by PySpark 2.4 package
      # It needs to be installed explicitly first
      - name: Install pre-req dependencies
        if: ${{ matrix.enviroment.PYPANDOC }}
        run: |
          cd trac-runtime/python
          python -m pip install --upgrade pip
          pip install pypandoc

      - name: Install dependencies
        run: |
          cd trac-runtime/python
          python -m pip install --upgrade pip
          pip install "pyspark ${{ matrix.enviroment.PYSPARK_VERSION }}"
          pip install "pandas ${{ matrix.enviroment.PANDAS_VERSION }}"
          pip install -r requirements.txt

      - name: Protoc code generation
        run: |
          cd trac-runtime/python
          python codegen/protoc-ctrl.py --domain
          python codegen/protoc-ctrl.py --proto

      - name: Unit tests
        run: |
          export PYTHONPATH=trac-runtime/python/generated
          export PYTHONPATH=trac-runtime/python/src:$PYTHONPATH
          export PYTHONPATH=trac-runtime/python/test:$PYTHONPATH
          python -m unittest discover -s trac-runtime/python/test/trac_test -t trac-runtime/python/test

      - name: Build packages
        run: |
          cd trac-runtime/python
          python setup.py sdist bdist_wheel
